port : "8080"

db:
  host: "localhost"
  port: "5432"
  user: "jemal"
  dbname: "banking"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

kafka:
  brokers: "localhost:9092"



